# 예외  

프로그램 실행 중 어떠한 원인에 의해서 의도에 맞지 않는 작동을 하거나 비정상적으로 종료되는 경우가 있다.  

이러한 결과의 원인을 **프로그램 에러 또는 오류**라고 한다.  

발생시점에 따라 다음 3가지로 구분할 수 있다.  

- **컴파일 에러(Compile-time Error):** 컴파일 시에 발생하는 에러
- **런타임 에러(Runtime-Error):** 실행 시에 발생하는 에러
- **논리적 에러(Logical Error):** 실행은 되지만 의도와는 다르게 동작

작성한 소스코드를 컴파일 하면 컴파일러가 소스코드에 대한 오타나 잘못된 구문 등의 기본적인 검사를 수행해 오류가 있는지 알려준다.  

컴파일러가 알려준 오류들을 모두 수정해 컴파일을 성공적으로 마치고 나면 클래스 파일이 생성되고 실행이 가능하다.  

하지만 컴파일 오류 없이 성공적으로 실행했어도 에러가 발생하지 않는 것은 아니다.  

자바는 런타임이 발생할 수 있는 프로그램 오류를 다음 2가지로 분류했다.  

- **오류(Error):** 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
  - 시스템의 비정상적인 상황으로 발생.
  - 시스템 레벨에서 발생하기 때문에 심각한 수준.
  - 시스템의 메모리 부족(Out of Memory), 스택오버플로우(Stack Overflow) 등과 같이 JVM이나 서버의 시스템 문제로 발생.
  - 개발자가 오류발생 상황을 미리 예측하여 처리 불가능.
  - 오류가 발생하는 순간 프로그램(서비스)이 비정상 종료가 되므로 발생하지 않도록 해야함.

- **예외(Exception):** 프로그램 코드에 의해서 수습될 수 있는 미약한 오류
  - 개발자가 구현한 로직에서 발생.
  - 개발자가 구현한 로직 내부에서 발생하기 때문에 예외발생 상황을 미리 예측하여 처리 가능.
  - Checked Exception 과 Unchecked Exception 이 존재

## 자바에서 제공하는 예외 클래스 계층 구조  

<img src="/Java/image/exception.png" width="700" height="300">  

Exception은 Checked Exception과 Unchecked Exception으로 구분될 수 있다.  

RuntimeException을 상속하지 않는 클래스는 Checked Exception, 반대로 상속한 클래스는 Unchecked Exception으로 분류한다.  

#### # Checked Exception  

Checked Exception이 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다.  

#### # Unchecked Exception  

주로 프로그램에 오류가 있을 때 발생하도록 의도된 것들이다.  

## 예외를 처리하는 다양한 방법  

예외가 발생하면 Error든 Exception이든 어플리케이션을 종료시킨다.  

이때 어플리케이션을 강제로 종료 시킬 것인가 아니면 다른 작업을 진행할 것인가를 구현할 수 있다.  

#### # try-catch-finally  

```java
try {
    // 처리 로직
} catch (SomeException e) {
    // 예외 발생시 처리 로직
} finally {
    // 정상 진행 또는 예외 발생시에도 항상 실행될 마지막 로직
}
```

try 블록에는 예외 발생 가능성이 있는 코드를 작성하고, catch 블록에는 예외 발생 시 진행할 코드를 작성한다.  

finally 블록에는 예외 발생여부에 상관없이 항상 실행할 코드를 작성한다.  

실행 순서는 다음과 같다.  

- try 블록에서 예외가 발생하지 않으면 catch 블록을 거치지 않고 finally 블록의 코드를 실행
- try 블록에서 예외가 발생하면 catch 블록으로 넘어가 코드를 실행하고 finally 블록의 코드를 실행

하나의 try 블록에는 다음처럼 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch 블록을 제공할 수 있다.  

```java
try {

} catch (SomeException1 e) {

} catch (SomeException2 e) {

} ...
```

이때 주의점은 상위 예외가 하위 예외보다 아래에 위치해야 한다.  

하위 예외는 상위 예외에 속해있기 때문에 상위 예외를 하위 예외 아래에 구현할 필요가 없다.  

다음처럼 하나의 catch 블록에 여러 개의 예외를 작성할 수 있다.  

```java
try {
    // 처리 로직
} catch (SomeException e1 | FooException e2) {
    // SomeException 또는 FooException이 발생시 처리 로직
} ...
```

## 예외 발생시키기  

throw 키워드를 통해 고의로 예외를 발생시킬 수 있다.  

```java
public void foo() {
    throw new SomeException();
}
```

## 메소드에 예외 선언하기  

메소드에 예외를 선언하려면 선언부에 throws 키워드를 사용해 메소드 내에서 발생할 수 있는 예외를 적어주면 된다.  

```java
public void foo() throws FooException {
    ... 
}
```

예외가 여러 개일 경우 **,** 로 구분한다.  

throws는 해당 메소드에서 예외를 처리하지 않고 해당 메소드를 호출하는 쪽에서 예외를 처리하도록 책임을 전가한다.  

```java
public void foo() throws FooException() {
    int a = 1;
    if (a == 1) {
        throw new FooException();
    }
}

public void run() {
    try {
        foo();
    } catch (FooException e) {
        ...
    }
}
```

## 사용자정의 예외 만들기  

개발자가 필요에 따라 새로운 예외 클래스를 정의하여 사용할 수 있다.  

Exception 클래스 또는 RuntimeException 클래스를 상속해 커스텀한 예외를 만들 수 있다.  

```java
public void customException extends RuntimeException {
    ...
}
```

---

#### 📌 Reference  

- 자바의 정석 1 | 남궁성 저
- <https://www.nextree.co.kr/p3239/>
- <https://live-everyday.tistory.com/203>